tls:
  certificates:
    - certFile: /etc/traefik/dynamic/localhost+3.pem
      keyFile: /etc/traefik/dynamic/localhost+3-key.pem
  
  stores:
    default:
      defaultCertificate:
        certFile: /etc/traefik/dynamic/localhost+3.pem
        keyFile: /etc/traefik/dynamic/localhost+3-key.pem
  
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: false
